#!/bin/env python

from setuptools import setup, find_packages

setup(
    name="workScripts",
    version="0.1",
    python_requires='>=3.7.0',
    description="Just some work scripts",
    author="Julian Dosch",
    author_email="Dosch@bio.uni-frankfurt.de",
    url="https://github.com/JuRuDo/miscWorkscripts",
    packages=find_packages(),
    package_data={'': ['*']},
    install_requires=[
        'coreapi',
        'urllib3',
        'lxml',
    ],
    entry_points={
        'console_scripts': ["uniprot.IDmapper = miscWorkScripts.uniprot.IDmapperUNIPROT:main",
                            "oma.getGroup = miscWorkScripts.oma.getGroup:main",
                            "kegg.getAAseq = miscWorkScripts.kegg.getAAseq:main",
                            "transcriptDEA.mergeResults = miscWorkScripts.transcriptDEA.mergeResults:main",
                            "transcriptDEA.fixEnsIDs = miscWorkScripts.transcriptDEA.fixEnsIDs:main",
                            "transcriptDEA.fixEnsIDsGeneExp = miscWorkScripts.transcriptDEA.fixEnsIDsGeneExp:main",
                            "transcriptDEA.getASevents = miscWorkScripts.transcriptDEA.compExpTranscripts:main",
                            "transcriptDEA.plotEXP = miscWorkScripts.transcriptDEA.plotExp:main",
                            "transcriptDEA.getASgenes = miscWorkScripts.transcriptDEA.getASgenes:main",
                            "transcriptDEA.filterColumn = miscWorkScripts.transcriptDEA.getRowsById:main",
                            "transcriptDEA.createUniqueGeneIds = miscWorkScripts.transcriptDEA.unique_gene_id:main",
                            "transcriptDEA.cleanUnspecific = miscWorkScripts.transcriptDEA.removeUnspecificStrand:main",
                            "gsea.matchBGtoData = miscWorkScripts.gsea.matchBGtoData:main",
                            "dge.pca = miscWorkScripts.dge.pca:main",
                            "dge.pcaPlot = miscWorkScripts.dge.plotpca:main",
                            "misc.filerTable = miscWorkScripts.misc.filterTable:main",
                            "misc.ENSGtoGeneName = miscWorkScripts.misc.ENSGtoGeneName:main",
                            "misc.matchTables = miscWorkScripts.misc.matchTables:main",
                            "misc.DGEcompareranks = miscWorkScripts.misc.DGEcompareranks:main",
                            "misc.plotTSNE = miscWorkScripts.misc.plotTSNE:main",
                            ],
    },
    license="GPL-3.0",
    classifiers=[
        "Environment :: Console",
        "Development Status :: 3 - Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
    ],
)
